import Head from 'next/head'
import Image from 'next/image'
import { IBM_Plex_Serif } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import React from 'react'
import Landing from '../../components/landing'

const inter = IBM_Plex_Serif({ weight: '400', subsets: ['cyrillic'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen w-full flex flex-row'>
        <Landing />
      </main>
    </>
  )
}
